api_platform:
    title: "World Asellidae Database"
    version: 2.2
    show_webby: false
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    patch_formats:
        json: ["application/merge-patch+json"]
    swagger:
        versions: [3]
    formats:
        json: ["application/json"]
        jsonld: ["application/ld+json"]
        jsonapi: ["application/vnd.api+json"]
        html: ["text/html"]
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage # Default value
            client_enabled: true
            client_items_per_page: true
