# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener: true
  allowed_methods_listener: true
  # routing_loader: true
  body_converter:
    enabled: true
  view:
    view_response_listener:
      enabled: true
    formats: { json: true, xml: false, rss: false }
  serializer:
    serialize_null: true
  exception:
    enabled: true
    map_exception_codes: true
    serializer_error_renderer: true
    codes:
      Doctrine\ORM\EntityNotFoundException: HTTP_NOT_FOUND
      'Doctrine\DBAL\Exception\UniqueConstraintViolationException': HTTP_CONFLICT
    messages:
      Doctrine\ORM\EntityNotFoundException: true
      'Doctrine\DBAL\Exception\UniqueConstraintViolationException': true
  format_listener:
    rules:
      - {
          path: ^/api,
          prefer_extension: false,
          fallback_format: ~,
          priorities: [json],
        }
      - {
          path: "^/",
          priorities: ["html", "*/*"],
          fallback_format: ~,
          prefer_extension: true,
        }
