controllers:
  resource: ../../src/Controller/
  type: annotation
  prefix: /{_locale}
  requirements:
    _locale: "%app_locales%"

api:
  resource: ../../src/Controller/API/
  type: annotation
  prefix: /api

kernel:
  resource: ../../src/Kernel.php
  type: annotation
