<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211002133702 extends AbstractMigration {
  public function getDescription(): string {
    return 'Simplify many-to-many relationships and relate user metadata to actual users';
  }

  public function up(Schema $schema): void {
    // this up() migration is auto-generated, please modify it to your needs
    $this->addSql('DROP SEQUENCE chromatogram_is_processed_to_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE dna_is_extracted_by_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE external_biological_material_is_processed_by_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE external_biological_material_is_published_in_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE external_sequence_is_published_in_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE has_targeted_taxa_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE internal_biological_material_is_published_in_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE internal_biological_material_is_treated_by_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE internal_sequence_is_assembled_by_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE internal_sequence_is_published_in_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE motu_is_generated_by_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE pcr_is_done_by_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE sample_is_fixed_with_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE sampling_is_done_with_method_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE sampling_is_funded_by_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE sampling_is_performed_by_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE slide_is_mounted_by_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE source_is_entered_by_id_seq CASCADE');
    $this->addSql('DROP SEQUENCE species_is_identified_by_id_seq CASCADE');
    $this->addSql('ALTER TABLE chromatogram ADD CONSTRAINT FK_ECF77DCDCA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE chromatogram ADD CONSTRAINT FK_ECF77DCD85B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_ECF77DCDCA76135A ON chromatogram (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_ECF77DCD85B7874A ON chromatogram (update_user_name)');
    $this->addSql('ALTER TABLE composition_of_internal_biological_material ADD CONSTRAINT FK_F4251750CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE composition_of_internal_biological_material ADD CONSTRAINT FK_F425175085B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_F4251750CA76135A ON composition_of_internal_biological_material (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_F425175085B7874A ON composition_of_internal_biological_material (update_user_name)');
    $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C96685B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_5373C966CA76135A ON country (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_5373C96685B7874A ON country (update_user_name)');
    $this->addSql('ALTER TABLE dna ADD CONSTRAINT FK_7154AD09CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE dna ADD CONSTRAINT FK_7154AD0985B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_7154AD09CA76135A ON dna (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_7154AD0985B7874A ON dna (update_user_name)');
    $this->addSql('CREATE INDEX dna_code_adn ON dna (dna_code)');
    $this->addSql('ALTER TABLE dna_is_extracted_by DROP CONSTRAINT fk_23');
    $this->addSql('ALTER TABLE dna_is_extracted_by DROP id');
    $this->addSql('ALTER TABLE dna_is_extracted_by DROP date_of_creation');
    $this->addSql('ALTER TABLE dna_is_extracted_by DROP date_of_update');
    $this->addSql('ALTER TABLE dna_is_extracted_by DROP creation_user_name');
    $this->addSql('ALTER TABLE dna_is_extracted_by DROP update_user_name');
    $this->addSql('ALTER TABLE dna_is_extracted_by ADD CONSTRAINT FK_876D7FE1918A8D9 FOREIGN KEY (dna_fk) REFERENCES dna (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE dna_is_extracted_by ADD PRIMARY KEY (dna_fk, person_fk)');
    $this->addSql('ALTER INDEX idx_b786c5214b06319d RENAME TO IDX_876D7FE1918A8D9');
    $this->addSql('ALTER INDEX idx_b786c521b53cd04c RENAME TO IDX_876D7FE1365CBA19');
    $this->addSql('ALTER TABLE external_biological_material ADD CONSTRAINT FK_10E065BFCA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_biological_material ADD CONSTRAINT FK_10E065BF85B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_10E065BFCA76135A ON external_biological_material (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_10E065BF85B7874A ON external_biological_material (update_user_name)');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by DROP CONSTRAINT fk_52');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by DROP id');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by DROP date_of_creation');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by DROP date_of_update');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by DROP creation_user_name');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by DROP update_user_name');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by ADD CONSTRAINT FK_3CF0920C7E400C9 FOREIGN KEY (external_biological_material_fk) REFERENCES external_biological_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by ADD PRIMARY KEY (external_biological_material_fk, person_fk)');
    $this->addSql('ALTER INDEX idx_7d78636f40d80ecd RENAME TO IDX_3CF0920C7E400C9');
    $this->addSql('ALTER INDEX idx_7d78636fb53cd04c RENAME TO IDX_3CF0920C365CBA19');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in DROP CONSTRAINT fk_53');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in DROP CONSTRAINT fk_54');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in DROP id');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in DROP date_of_creation');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in DROP date_of_update');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in DROP creation_user_name');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in DROP update_user_name');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in ADD CONSTRAINT FK_611578F57E400C9 FOREIGN KEY (external_biological_material_fk) REFERENCES external_biological_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in ADD CONSTRAINT FK_611578F5821B1D3F FOREIGN KEY (source_fk) REFERENCES source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in ADD PRIMARY KEY (external_biological_material_fk, source_fk)');
    $this->addSql('ALTER INDEX idx_d2338bb240d80ecd RENAME TO IDX_611578F57E400C9');
    $this->addSql('ALTER INDEX idx_d2338bb2821b1d3f RENAME TO IDX_611578F5821B1D3F');
    $this->addSql('ALTER TABLE external_sequence ADD CONSTRAINT FK_BD8A65D8CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_sequence ADD CONSTRAINT FK_BD8A65D885B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_BD8A65D8CA76135A ON external_sequence (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_BD8A65D885B7874A ON external_sequence (update_user_name)');
    $this->addSql('ALTER TABLE external_sequence_is_entered_by DROP CONSTRAINT fk_31');
    $this->addSql('ALTER TABLE external_sequence_is_entered_by ADD CONSTRAINT FK_E3B7BF44E71B5587 FOREIGN KEY (external_sequence_fk) REFERENCES external_sequence (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_sequence_is_entered_by ADD PRIMARY KEY (external_sequence_fk, person_fk)');
    $this->addSql('ALTER INDEX idx_dc41e25acdd1f756 RENAME TO IDX_E3B7BF44E71B5587');
    $this->addSql('ALTER INDEX idx_dc41e25ab53cd04c RENAME TO IDX_E3B7BF44365CBA19');
    $this->addSql('ALTER TABLE external_sequence_is_published_in DROP CONSTRAINT fk_7');
    $this->addSql('ALTER TABLE external_sequence_is_published_in DROP CONSTRAINT fk_8');
    $this->addSql('ALTER TABLE external_sequence_is_published_in DROP id');
    $this->addSql('ALTER TABLE external_sequence_is_published_in DROP date_of_creation');
    $this->addSql('ALTER TABLE external_sequence_is_published_in DROP date_of_update');
    $this->addSql('ALTER TABLE external_sequence_is_published_in DROP creation_user_name');
    $this->addSql('ALTER TABLE external_sequence_is_published_in DROP update_user_name');
    $this->addSql('ALTER TABLE external_sequence_is_published_in ADD CONSTRAINT FK_AF7F5629E71B5587 FOREIGN KEY (external_sequence_fk) REFERENCES external_sequence (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_sequence_is_published_in ADD CONSTRAINT FK_AF7F5629821B1D3F FOREIGN KEY (source_fk) REFERENCES source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_sequence_is_published_in ADD PRIMARY KEY (external_sequence_fk, source_fk)');
    $this->addSql('ALTER INDEX idx_8d0e8d6acdd1f756 RENAME TO IDX_AF7F5629E71B5587');
    $this->addSql('ALTER INDEX idx_8d0e8d6a821b1d3f RENAME TO IDX_AF7F5629821B1D3F');
    $this->addSql('ALTER TABLE identified_species ADD CONSTRAINT FK_801C3911CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE identified_species ADD CONSTRAINT FK_801C391185B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_801C3911CA76135A ON identified_species (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_801C391185B7874A ON identified_species (update_user_name)');
    $this->addSql('ALTER TABLE species_is_identified_by DROP CONSTRAINT fk_9');
    $this->addSql('ALTER TABLE species_is_identified_by DROP id');
    $this->addSql('ALTER TABLE species_is_identified_by DROP date_of_creation');
    $this->addSql('ALTER TABLE species_is_identified_by DROP date_of_update');
    $this->addSql('ALTER TABLE species_is_identified_by DROP creation_user_name');
    $this->addSql('ALTER TABLE species_is_identified_by DROP update_user_name');
    $this->addSql('ALTER TABLE species_is_identified_by ADD CONSTRAINT FK_F14051CB7607DC5C FOREIGN KEY (identified_species_fk) REFERENCES identified_species (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE species_is_identified_by ADD PRIMARY KEY (identified_species_fk, person_fk)');
    $this->addSql('ALTER INDEX idx_f8fccf63b4ab6ba0 RENAME TO IDX_F14051CB7607DC5C');
    $this->addSql('ALTER INDEX idx_f8fccf63b53cd04c RENAME TO IDX_F14051CB365CBA19');
    $this->addSql('ALTER TABLE institution ADD CONSTRAINT FK_3A9F98E5CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE institution ADD CONSTRAINT FK_3A9F98E585B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_3A9F98E5CA76135A ON institution (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_3A9F98E585B7874A ON institution (update_user_name)');
    $this->addSql('ALTER TABLE internal_biological_material ADD CONSTRAINT FK_F9B58FB1CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_biological_material ADD CONSTRAINT FK_F9B58FB185B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_F9B58FB1CA76135A ON internal_biological_material (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_F9B58FB185B7874A ON internal_biological_material (update_user_name)');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by DROP CONSTRAINT fk_27');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by DROP id');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by DROP date_of_creation');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by DROP date_of_update');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by DROP creation_user_name');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by DROP update_user_name');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by ADD CONSTRAINT FK_45493852B2EA9337 FOREIGN KEY (internal_biological_material_fk) REFERENCES internal_biological_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by ADD PRIMARY KEY (internal_biological_material_fk, person_fk)');
    $this->addSql('ALTER INDEX idx_69c58aff54dbbd4d RENAME TO IDX_45493852B2EA9337');
    $this->addSql('ALTER INDEX idx_69c58affb53cd04c RENAME TO IDX_45493852365CBA19');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in DROP CONSTRAINT fk_44');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in DROP CONSTRAINT fk_45');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in DROP id');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in DROP date_of_creation');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in DROP date_of_update');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in DROP creation_user_name');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in DROP update_user_name');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in ADD CONSTRAINT FK_A0851641B2EA9337 FOREIGN KEY (internal_biological_material_fk) REFERENCES internal_biological_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in ADD CONSTRAINT FK_A0851641821B1D3F FOREIGN KEY (source_fk) REFERENCES source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in ADD PRIMARY KEY (internal_biological_material_fk, source_fk)');
    $this->addSql('ALTER INDEX idx_ea07bfa754dbbd4d RENAME TO IDX_A0851641B2EA9337');
    $this->addSql('ALTER INDEX idx_ea07bfa7821b1d3f RENAME TO IDX_A0851641821B1D3F');
    $this->addSql('ALTER TABLE internal_sequence ADD CONSTRAINT FK_9D245AF3CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_sequence ADD CONSTRAINT FK_9D245AF385B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_9D245AF3CA76135A ON internal_sequence (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_9D245AF385B7874A ON internal_sequence (update_user_name)');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by DROP CONSTRAINT fk_19');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by DROP id');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by DROP date_of_creation');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by DROP date_of_update');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by DROP creation_user_name');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by DROP update_user_name');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by ADD CONSTRAINT FK_E9D45D2DBAB35875 FOREIGN KEY (internal_sequence_fk) REFERENCES internal_sequence (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by ADD PRIMARY KEY (internal_sequence_fk, person_fk)');
    $this->addSql('ALTER INDEX idx_f6971ba85be90e48 RENAME TO IDX_E9D45D2DBAB35875');
    $this->addSql('ALTER INDEX idx_f6971ba8b53cd04c RENAME TO IDX_E9D45D2D365CBA19');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in DROP CONSTRAINT fk_');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in DROP CONSTRAINT fk_1');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in DROP id');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in DROP date_of_creation');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in DROP date_of_update');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in DROP creation_user_name');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in DROP update_user_name');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in ADD CONSTRAINT FK_4C46EDEABAB35875 FOREIGN KEY (internal_sequence_fk) REFERENCES internal_sequence (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in ADD CONSTRAINT FK_4C46EDEA821B1D3F FOREIGN KEY (source_fk) REFERENCES source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in ADD PRIMARY KEY (internal_sequence_fk, source_fk)');
    $this->addSql('ALTER INDEX idx_ba97b9c45be90e48 RENAME TO IDX_4C46EDEABAB35875');
    $this->addSql('ALTER INDEX idx_ba97b9c4821b1d3f RENAME TO IDX_4C46EDEA821B1D3F');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to DROP CONSTRAINT fk_38');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to DROP id');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to DROP date_of_creation');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to DROP date_of_update');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to DROP creation_user_name');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to DROP update_user_name');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to ADD CONSTRAINT FK_84CA21FCBAB35875 FOREIGN KEY (internal_sequence_fk) REFERENCES internal_sequence (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to ADD PRIMARY KEY (internal_sequence_fk, chromatogram_fk)');
    $this->addSql('ALTER INDEX idx_bd45639e5be90e48 RENAME TO IDX_84CA21FCBAB35875');
    $this->addSql('ALTER INDEX idx_bd45639eefcfd332 RENAME TO IDX_84CA21FC5159A195');
    $this->addSql('ALTER TABLE motu ADD CONSTRAINT FK_C0BF459ECA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE motu ADD CONSTRAINT FK_C0BF459E85B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE UNIQUE INDEX UNIQ_C0BF459EC2CFFC71 ON motu (motu_title)');
    $this->addSql('CREATE INDEX IDX_C0BF459ECA76135A ON motu (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_C0BF459E85B7874A ON motu (update_user_name)');
    $this->addSql('ALTER TABLE motu_is_generated_by DROP CONSTRAINT fk_33');
    $this->addSql('ALTER TABLE motu_is_generated_by DROP id');
    $this->addSql('ALTER TABLE motu_is_generated_by DROP date_of_creation');
    $this->addSql('ALTER TABLE motu_is_generated_by DROP date_of_update');
    $this->addSql('ALTER TABLE motu_is_generated_by DROP creation_user_name');
    $this->addSql('ALTER TABLE motu_is_generated_by DROP update_user_name');
    $this->addSql('ALTER TABLE motu_is_generated_by ADD CONSTRAINT FK_2DB26991503B4409 FOREIGN KEY (motu_fk) REFERENCES motu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE motu_is_generated_by ADD PRIMARY KEY (motu_fk, person_fk)');
    $this->addSql('ALTER INDEX idx_17a90ea3503b4409 RENAME TO IDX_2DB26991503B4409');
    $this->addSql('ALTER INDEX idx_17a90ea3b53cd04c RENAME TO IDX_2DB26991365CBA19');
    $this->addSql('ALTER TABLE motu_number ADD CONSTRAINT FK_6B1B1FAACA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE motu_number ADD CONSTRAINT FK_6B1B1FAA85B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_6B1B1FAACA76135A ON motu_number (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_6B1B1FAA85B7874A ON motu_number (update_user_name)');
    $this->addSql('ALTER TABLE municipality ADD CONSTRAINT FK_C6F56628CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE municipality ADD CONSTRAINT FK_C6F5662885B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_C6F56628CA76135A ON municipality (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_C6F5662885B7874A ON municipality (update_user_name)');
    $this->addSql('ALTER TABLE pcr ADD CONSTRAINT FK_5B6B9936CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE pcr ADD CONSTRAINT FK_5B6B993685B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_5B6B9936CA76135A ON pcr (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_5B6B993685B7874A ON pcr (update_user_name)');
    $this->addSql('ALTER TABLE pcr_is_done_by DROP CONSTRAINT fk_21');
    $this->addSql('ALTER TABLE pcr_is_done_by DROP id');
    $this->addSql('ALTER TABLE pcr_is_done_by DROP date_of_creation');
    $this->addSql('ALTER TABLE pcr_is_done_by DROP date_of_update');
    $this->addSql('ALTER TABLE pcr_is_done_by DROP creation_user_name');
    $this->addSql('ALTER TABLE pcr_is_done_by DROP update_user_name');
    $this->addSql('ALTER TABLE pcr_is_done_by ADD CONSTRAINT FK_7653C90F2B63D494 FOREIGN KEY (pcr_fk) REFERENCES pcr (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE pcr_is_done_by ADD PRIMARY KEY (pcr_fk, person_fk)');
    $this->addSql('ALTER INDEX idx_1041853b2b63d494 RENAME TO IDX_7653C90F2B63D494');
    $this->addSql('ALTER INDEX idx_1041853bb53cd04c RENAME TO IDX_7653C90F365CBA19');
    $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD17685B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_34DCD176CA76135A ON person (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_34DCD17685B7874A ON person (update_user_name)');
    $this->addSql('ALTER TABLE program ADD CONSTRAINT FK_92ED7784CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE program ADD CONSTRAINT FK_92ED778485B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_92ED7784CA76135A ON program (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_92ED778485B7874A ON program (update_user_name)');
    $this->addSql('ALTER TABLE sampling ADD CONSTRAINT FK_39DAF8C6CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE sampling ADD CONSTRAINT FK_39DAF8C685B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_39DAF8C6CA76135A ON sampling (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_39DAF8C685B7874A ON sampling (update_user_name)');
    $this->addSql('ALTER TABLE sampling_is_done_with_method DROP CONSTRAINT fk_41');
    $this->addSql('ALTER TABLE sampling_is_done_with_method DROP id');
    $this->addSql('ALTER TABLE sampling_is_done_with_method DROP date_of_creation');
    $this->addSql('ALTER TABLE sampling_is_done_with_method DROP date_of_update');
    $this->addSql('ALTER TABLE sampling_is_done_with_method DROP creation_user_name');
    $this->addSql('ALTER TABLE sampling_is_done_with_method DROP update_user_name');
    $this->addSql('ALTER TABLE sampling_is_done_with_method ADD CONSTRAINT FK_720F2A4F5E277EDA FOREIGN KEY (sampling_fk) REFERENCES sampling (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE sampling_is_done_with_method ADD PRIMARY KEY (sampling_fk, sampling_method_voc_fk)');
    $this->addSql('ALTER INDEX idx_5a6bd88a662d9b98 RENAME TO IDX_720F2A4F5E277EDA');
    $this->addSql('ALTER INDEX idx_5a6bd88a29b38195 RENAME TO IDX_720F2A4F29B38195');
    $this->addSql('ALTER TABLE sample_is_fixed_with DROP CONSTRAINT fk_43');
    $this->addSql('ALTER TABLE sample_is_fixed_with DROP id');
    $this->addSql('ALTER TABLE sample_is_fixed_with DROP date_of_creation');
    $this->addSql('ALTER TABLE sample_is_fixed_with DROP date_of_update');
    $this->addSql('ALTER TABLE sample_is_fixed_with DROP creation_user_name');
    $this->addSql('ALTER TABLE sample_is_fixed_with DROP update_user_name');
    $this->addSql('ALTER TABLE sample_is_fixed_with ADD CONSTRAINT FK_1645AC245E277EDA FOREIGN KEY (sampling_fk) REFERENCES sampling (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE sample_is_fixed_with ADD PRIMARY KEY (sampling_fk, fixative_voc_fk)');
    $this->addSql('ALTER INDEX idx_60129a31662d9b98 RENAME TO IDX_1645AC245E277EDA');
    $this->addSql('ALTER INDEX idx_60129a315fd841ac RENAME TO IDX_1645AC24A17A5D5');
    $this->addSql('ALTER TABLE sampling_is_funded_by DROP CONSTRAINT fk_101');
    $this->addSql('ALTER TABLE sampling_is_funded_by DROP id');
    $this->addSql('ALTER TABLE sampling_is_funded_by DROP date_of_creation');
    $this->addSql('ALTER TABLE sampling_is_funded_by DROP date_of_update');
    $this->addSql('ALTER TABLE sampling_is_funded_by DROP creation_user_name');
    $this->addSql('ALTER TABLE sampling_is_funded_by DROP update_user_name');
    $this->addSql('ALTER TABLE sampling_is_funded_by ADD CONSTRAINT FK_427EDD595E277EDA FOREIGN KEY (sampling_fk) REFERENCES sampling (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE sampling_is_funded_by ADD PRIMARY KEY (sampling_fk, program_fk)');
    $this->addSql('ALTER INDEX idx_18fcbb8f662d9b98 RENAME TO IDX_427EDD595E277EDA');
    $this->addSql('ALTER INDEX idx_18fcbb8f759c7bb0 RENAME TO IDX_427EDD59299F0654');
    $this->addSql('ALTER TABLE sampling_is_performed_by DROP CONSTRAINT fk_65');
    $this->addSql('ALTER TABLE sampling_is_performed_by DROP id');
    $this->addSql('ALTER TABLE sampling_is_performed_by DROP date_of_creation');
    $this->addSql('ALTER TABLE sampling_is_performed_by DROP date_of_update');
    $this->addSql('ALTER TABLE sampling_is_performed_by DROP creation_user_name');
    $this->addSql('ALTER TABLE sampling_is_performed_by DROP update_user_name');
    $this->addSql('ALTER TABLE sampling_is_performed_by ADD CONSTRAINT FK_946D07C95E277EDA FOREIGN KEY (sampling_fk) REFERENCES sampling (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE sampling_is_performed_by ADD PRIMARY KEY (sampling_fk, person_fk)');
    $this->addSql('ALTER INDEX idx_ee2a88c9662d9b98 RENAME TO IDX_946D07C95E277EDA');
    $this->addSql('ALTER INDEX idx_ee2a88c9b53cd04c RENAME TO IDX_946D07C9365CBA19');
    $this->addSql('ALTER TABLE has_targeted_taxa DROP CONSTRAINT fk_17');
    $this->addSql('ALTER TABLE has_targeted_taxa DROP id');
    $this->addSql('ALTER TABLE has_targeted_taxa DROP date_of_creation');
    $this->addSql('ALTER TABLE has_targeted_taxa DROP date_of_update');
    $this->addSql('ALTER TABLE has_targeted_taxa DROP creation_user_name');
    $this->addSql('ALTER TABLE has_targeted_taxa DROP update_user_name');
    $this->addSql('ALTER TABLE has_targeted_taxa ADD CONSTRAINT FK_4F1FE1B25E277EDA FOREIGN KEY (sampling_fk) REFERENCES sampling (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE has_targeted_taxa ADD PRIMARY KEY (sampling_fk, taxon_fk)');
    $this->addSql('ALTER INDEX idx_c0df0ce4662d9b98 RENAME TO IDX_4F1FE1B25E277EDA');
    $this->addSql('ALTER INDEX idx_c0df0ce47b09e3bc RENAME TO IDX_4F1FE1B2C934F52E');
    $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E4CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E485B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_694309E4CA76135A ON site (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_694309E485B7874A ON site (update_user_name)');
    $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F73CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F7385B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_5F8A7F73CA76135A ON source (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_5F8A7F7385B7874A ON source (update_user_name)');
    $this->addSql('ALTER TABLE source_is_entered_by DROP CONSTRAINT fk_29');
    $this->addSql('ALTER TABLE source_is_entered_by DROP id');
    $this->addSql('ALTER TABLE source_is_entered_by DROP date_of_creation');
    $this->addSql('ALTER TABLE source_is_entered_by DROP date_of_update');
    $this->addSql('ALTER TABLE source_is_entered_by DROP creation_user_name');
    $this->addSql('ALTER TABLE source_is_entered_by DROP update_user_name');
    $this->addSql('ALTER TABLE source_is_entered_by ADD CONSTRAINT FK_1399C909821B1D3F FOREIGN KEY (source_fk) REFERENCES source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE source_is_entered_by ADD PRIMARY KEY (source_fk, person_fk)');
    $this->addSql('ALTER INDEX idx_16dc6005821b1d3f RENAME TO IDX_1399C909821B1D3F');
    $this->addSql('ALTER INDEX idx_16dc6005b53cd04c RENAME TO IDX_1399C909365CBA19');
    $this->addSql('ALTER TABLE specimen ADD CONSTRAINT FK_999F3902CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE specimen ADD CONSTRAINT FK_999F390285B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_999F3902CA76135A ON specimen (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_999F390285B7874A ON specimen (update_user_name)');
    $this->addSql('ALTER TABLE specimen_slide ADD CONSTRAINT FK_ECF0B8FCA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE specimen_slide ADD CONSTRAINT FK_ECF0B8F85B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_ECF0B8FCA76135A ON specimen_slide (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_ECF0B8F85B7874A ON specimen_slide (update_user_name)');
    $this->addSql('ALTER TABLE slide_is_mounted_by DROP CONSTRAINT fk_25');
    $this->addSql('ALTER TABLE slide_is_mounted_by DROP id');
    $this->addSql('ALTER TABLE slide_is_mounted_by DROP date_of_creation');
    $this->addSql('ALTER TABLE slide_is_mounted_by DROP date_of_update');
    $this->addSql('ALTER TABLE slide_is_mounted_by DROP creation_user_name');
    $this->addSql('ALTER TABLE slide_is_mounted_by DROP update_user_name');
    $this->addSql('ALTER TABLE slide_is_mounted_by ADD CONSTRAINT FK_C07E745D73209E37 FOREIGN KEY (specimen_slide_fk) REFERENCES specimen_slide (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE slide_is_mounted_by ADD PRIMARY KEY (specimen_slide_fk, person_fk)');
    $this->addSql('ALTER INDEX idx_88295540d9c85992 RENAME TO IDX_C07E745D73209E37');
    $this->addSql('ALTER INDEX idx_88295540b53cd04c RENAME TO IDX_C07E745D365CBA19');
    $this->addSql('ALTER TABLE storage_box ADD CONSTRAINT FK_932E7636CA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE storage_box ADD CONSTRAINT FK_932E763685B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_932E7636CA76135A ON storage_box (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_932E763685B7874A ON storage_box (update_user_name)');
    $this->addSql('ALTER TABLE taxon ADD CONSTRAINT FK_5B6723ABCA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE taxon ADD CONSTRAINT FK_5B6723AB85B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_5B6723ABCA76135A ON taxon (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_5B6723AB85B7874A ON taxon (update_user_name)');
    $this->addSql('ALTER TABLE user_db ADD CONSTRAINT FK_FBA308EDCA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE user_db ADD CONSTRAINT FK_FBA308ED85B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_FBA308EDCA76135A ON user_db (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_FBA308ED85B7874A ON user_db (update_user_name)');
    $this->addSql('ALTER TABLE vocabulary ADD CONSTRAINT FK_9099C97BCA76135A FOREIGN KEY (creation_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE vocabulary ADD CONSTRAINT FK_9099C97B85B7874A FOREIGN KEY (update_user_name) REFERENCES user_db (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('CREATE INDEX IDX_9099C97BCA76135A ON vocabulary (creation_user_name)');
    $this->addSql('CREATE INDEX IDX_9099C97B85B7874A ON vocabulary (update_user_name)');
  }

  public function down(Schema $schema): void {
    // this down() migration is auto-generated, please modify it to your needs
    $this->addSql('CREATE SCHEMA public');
    $this->addSql('CREATE SEQUENCE chromatogram_is_processed_to_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE dna_is_extracted_by_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE external_biological_material_is_processed_by_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE external_biological_material_is_published_in_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE external_sequence_is_published_in_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE has_targeted_taxa_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE internal_biological_material_is_published_in_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE internal_biological_material_is_treated_by_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE internal_sequence_is_assembled_by_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE internal_sequence_is_published_in_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE motu_is_generated_by_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE pcr_is_done_by_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE sample_is_fixed_with_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE sampling_is_done_with_method_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE sampling_is_funded_by_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE sampling_is_performed_by_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE slide_is_mounted_by_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE source_is_entered_by_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE SEQUENCE species_is_identified_by_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('ALTER TABLE country DROP CONSTRAINT FK_5373C966CA76135A');
    $this->addSql('ALTER TABLE country DROP CONSTRAINT FK_5373C96685B7874A');
    $this->addSql('DROP INDEX IDX_5373C966CA76135A');
    $this->addSql('DROP INDEX IDX_5373C96685B7874A');
    $this->addSql('ALTER TABLE has_targeted_taxa DROP CONSTRAINT FK_4F1FE1B25E277EDA');
    $this->addSql('DROP INDEX pk_has_targeted_taxa');
    $this->addSql('ALTER TABLE has_targeted_taxa ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE has_targeted_taxa ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE has_targeted_taxa ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE has_targeted_taxa ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE has_targeted_taxa ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE has_targeted_taxa ADD CONSTRAINT fk_17 FOREIGN KEY (sampling_fk) REFERENCES sampling (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE has_targeted_taxa ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_4f1fe1b2c934f52e RENAME TO idx_c0df0ce47b09e3bc');
    $this->addSql('ALTER INDEX idx_4f1fe1b25e277eda RENAME TO idx_c0df0ce4662d9b98');
    $this->addSql('ALTER TABLE external_biological_material DROP CONSTRAINT FK_10E065BFCA76135A');
    $this->addSql('ALTER TABLE external_biological_material DROP CONSTRAINT FK_10E065BF85B7874A');
    $this->addSql('DROP INDEX IDX_10E065BFCA76135A');
    $this->addSql('DROP INDEX IDX_10E065BF85B7874A');
    $this->addSql('ALTER TABLE external_sequence_is_entered_by DROP CONSTRAINT FK_E3B7BF44E71B5587');
    $this->addSql('ALTER TABLE external_sequence_is_entered_by ADD CONSTRAINT fk_31 FOREIGN KEY (external_sequence_fk) REFERENCES external_sequence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER INDEX idx_e3b7bf44365cba19 RENAME TO idx_dc41e25ab53cd04c');
    $this->addSql('ALTER INDEX idx_e3b7bf44e71b5587 RENAME TO idx_dc41e25acdd1f756');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by DROP CONSTRAINT FK_3CF0920C7E400C9');
    $this->addSql('DROP INDEX pk_external_biological_material_is_processed_by');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by ADD CONSTRAINT fk_52 FOREIGN KEY (external_biological_material_fk) REFERENCES external_biological_material (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_biological_material_is_processed_by ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_3cf0920c365cba19 RENAME TO idx_7d78636fb53cd04c');
    $this->addSql('ALTER INDEX idx_3cf0920c7e400c9 RENAME TO idx_7d78636f40d80ecd');
    $this->addSql('ALTER TABLE composition_of_internal_biological_material DROP CONSTRAINT FK_F4251750CA76135A');
    $this->addSql('ALTER TABLE composition_of_internal_biological_material DROP CONSTRAINT FK_F425175085B7874A');
    $this->addSql('DROP INDEX IDX_F4251750CA76135A');
    $this->addSql('DROP INDEX IDX_F425175085B7874A');
    $this->addSql('ALTER TABLE external_sequence DROP CONSTRAINT FK_BD8A65D8CA76135A');
    $this->addSql('ALTER TABLE external_sequence DROP CONSTRAINT FK_BD8A65D885B7874A');
    $this->addSql('DROP INDEX IDX_BD8A65D8CA76135A');
    $this->addSql('DROP INDEX IDX_BD8A65D885B7874A');
    $this->addSql('ALTER TABLE dna DROP CONSTRAINT FK_7154AD09CA76135A');
    $this->addSql('ALTER TABLE dna DROP CONSTRAINT FK_7154AD0985B7874A');
    $this->addSql('DROP INDEX IDX_7154AD09CA76135A');
    $this->addSql('DROP INDEX IDX_7154AD0985B7874A');
    $this->addSql('DROP INDEX dna_code_adn');
    $this->addSql('ALTER TABLE chromatogram DROP CONSTRAINT FK_ECF77DCDCA76135A');
    $this->addSql('ALTER TABLE chromatogram DROP CONSTRAINT FK_ECF77DCD85B7874A');
    $this->addSql('DROP INDEX IDX_ECF77DCDCA76135A');
    $this->addSql('DROP INDEX IDX_ECF77DCD85B7874A');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to DROP CONSTRAINT FK_84CA21FCBAB35875');
    $this->addSql('DROP INDEX pk_chromatogram_is_processed_to');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to ADD CONSTRAINT fk_38 FOREIGN KEY (internal_sequence_fk) REFERENCES internal_sequence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE chromatogram_is_processed_to ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_84ca21fcbab35875 RENAME TO idx_bd45639e5be90e48');
    $this->addSql('ALTER INDEX idx_84ca21fc5159a195 RENAME TO idx_bd45639eefcfd332');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in DROP CONSTRAINT FK_611578F57E400C9');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in DROP CONSTRAINT FK_611578F5821B1D3F');
    $this->addSql('DROP INDEX pk_external_biological_material_is_published_in');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in ADD CONSTRAINT fk_53 FOREIGN KEY (external_biological_material_fk) REFERENCES external_biological_material (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in ADD CONSTRAINT fk_54 FOREIGN KEY (source_fk) REFERENCES source (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_biological_material_is_published_in ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_611578f5821b1d3f RENAME TO idx_d2338bb2821b1d3f');
    $this->addSql('ALTER INDEX idx_611578f57e400c9 RENAME TO idx_d2338bb240d80ecd');
    $this->addSql('ALTER TABLE external_sequence_is_published_in DROP CONSTRAINT FK_AF7F5629E71B5587');
    $this->addSql('ALTER TABLE external_sequence_is_published_in DROP CONSTRAINT FK_AF7F5629821B1D3F');
    $this->addSql('DROP INDEX pk_external_sequence_is_published_in');
    $this->addSql('ALTER TABLE external_sequence_is_published_in ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE external_sequence_is_published_in ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE external_sequence_is_published_in ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE external_sequence_is_published_in ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE external_sequence_is_published_in ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE external_sequence_is_published_in ADD CONSTRAINT fk_7 FOREIGN KEY (source_fk) REFERENCES source (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_sequence_is_published_in ADD CONSTRAINT fk_8 FOREIGN KEY (external_sequence_fk) REFERENCES external_sequence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE external_sequence_is_published_in ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_af7f5629e71b5587 RENAME TO idx_8d0e8d6acdd1f756');
    $this->addSql('ALTER INDEX idx_af7f5629821b1d3f RENAME TO idx_8d0e8d6a821b1d3f');
    $this->addSql('ALTER TABLE identified_species DROP CONSTRAINT FK_801C3911CA76135A');
    $this->addSql('ALTER TABLE identified_species DROP CONSTRAINT FK_801C391185B7874A');
    $this->addSql('DROP INDEX IDX_801C3911CA76135A');
    $this->addSql('DROP INDEX IDX_801C391185B7874A');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by DROP CONSTRAINT FK_45493852B2EA9337');
    $this->addSql('DROP INDEX pk_internal_biological_material_is_treated_by');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by ADD CONSTRAINT fk_27 FOREIGN KEY (internal_biological_material_fk) REFERENCES internal_biological_material (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_biological_material_is_treated_by ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_45493852b2ea9337 RENAME TO idx_69c58aff54dbbd4d');
    $this->addSql('ALTER INDEX idx_45493852365cba19 RENAME TO idx_69c58affb53cd04c');
    $this->addSql('ALTER TABLE internal_biological_material DROP CONSTRAINT FK_F9B58FB1CA76135A');
    $this->addSql('ALTER TABLE internal_biological_material DROP CONSTRAINT FK_F9B58FB185B7874A');
    $this->addSql('DROP INDEX IDX_F9B58FB1CA76135A');
    $this->addSql('DROP INDEX IDX_F9B58FB185B7874A');
    $this->addSql('ALTER TABLE internal_sequence DROP CONSTRAINT FK_9D245AF3CA76135A');
    $this->addSql('ALTER TABLE internal_sequence DROP CONSTRAINT FK_9D245AF385B7874A');
    $this->addSql('DROP INDEX IDX_9D245AF3CA76135A');
    $this->addSql('DROP INDEX IDX_9D245AF385B7874A');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in DROP CONSTRAINT FK_A0851641B2EA9337');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in DROP CONSTRAINT FK_A0851641821B1D3F');
    $this->addSql('DROP INDEX pk_internal_biological_material_is_published_in');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in ADD CONSTRAINT fk_44 FOREIGN KEY (internal_biological_material_fk) REFERENCES internal_biological_material (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in ADD CONSTRAINT fk_45 FOREIGN KEY (source_fk) REFERENCES source (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_biological_material_is_published_in ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_a0851641821b1d3f RENAME TO idx_ea07bfa7821b1d3f');
    $this->addSql('ALTER INDEX idx_a0851641b2ea9337 RENAME TO idx_ea07bfa754dbbd4d');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by DROP CONSTRAINT FK_E9D45D2DBAB35875');
    $this->addSql('DROP INDEX pk_internal_sequence_is_assembled_by');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by ADD CONSTRAINT fk_19 FOREIGN KEY (internal_sequence_fk) REFERENCES internal_sequence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_sequence_is_assembled_by ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_e9d45d2d365cba19 RENAME TO idx_f6971ba8b53cd04c');
    $this->addSql('ALTER INDEX idx_e9d45d2dbab35875 RENAME TO idx_f6971ba85be90e48');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in DROP CONSTRAINT FK_4C46EDEABAB35875');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in DROP CONSTRAINT FK_4C46EDEA821B1D3F');
    $this->addSql('DROP INDEX pk_internal_sequence_is_published_in');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in ADD CONSTRAINT fk_ FOREIGN KEY (source_fk) REFERENCES source (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in ADD CONSTRAINT fk_1 FOREIGN KEY (internal_sequence_fk) REFERENCES internal_sequence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE internal_sequence_is_published_in ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_4c46edea821b1d3f RENAME TO idx_ba97b9c4821b1d3f');
    $this->addSql('ALTER INDEX idx_4c46edeabab35875 RENAME TO idx_ba97b9c45be90e48');
    $this->addSql('ALTER TABLE motu_number DROP CONSTRAINT FK_6B1B1FAACA76135A');
    $this->addSql('ALTER TABLE motu_number DROP CONSTRAINT FK_6B1B1FAA85B7874A');
    $this->addSql('DROP INDEX IDX_6B1B1FAACA76135A');
    $this->addSql('DROP INDEX IDX_6B1B1FAA85B7874A');
    $this->addSql('ALTER TABLE motu DROP CONSTRAINT FK_C0BF459ECA76135A');
    $this->addSql('ALTER TABLE motu DROP CONSTRAINT FK_C0BF459E85B7874A');
    $this->addSql('DROP INDEX UNIQ_C0BF459EC2CFFC71');
    $this->addSql('DROP INDEX IDX_C0BF459ECA76135A');
    $this->addSql('DROP INDEX IDX_C0BF459E85B7874A');
    $this->addSql('ALTER TABLE motu_is_generated_by DROP CONSTRAINT FK_2DB26991503B4409');
    $this->addSql('DROP INDEX pk_motu_is_generated_by');
    $this->addSql('ALTER TABLE motu_is_generated_by ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE motu_is_generated_by ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE motu_is_generated_by ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE motu_is_generated_by ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE motu_is_generated_by ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE motu_is_generated_by ADD CONSTRAINT fk_33 FOREIGN KEY (motu_fk) REFERENCES motu (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE motu_is_generated_by ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_2db26991503b4409 RENAME TO idx_17a90ea3503b4409');
    $this->addSql('ALTER INDEX idx_2db26991365cba19 RENAME TO idx_17a90ea3b53cd04c');
    $this->addSql('ALTER TABLE slide_is_mounted_by DROP CONSTRAINT FK_C07E745D73209E37');
    $this->addSql('DROP INDEX pk_slide_is_mounted_by');
    $this->addSql('ALTER TABLE slide_is_mounted_by ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE slide_is_mounted_by ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE slide_is_mounted_by ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE slide_is_mounted_by ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE slide_is_mounted_by ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE slide_is_mounted_by ADD CONSTRAINT fk_25 FOREIGN KEY (specimen_slide_fk) REFERENCES specimen_slide (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE slide_is_mounted_by ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_c07e745d73209e37 RENAME TO idx_88295540d9c85992');
    $this->addSql('ALTER INDEX idx_c07e745d365cba19 RENAME TO idx_88295540b53cd04c');
    $this->addSql('ALTER TABLE program DROP CONSTRAINT FK_92ED7784CA76135A');
    $this->addSql('ALTER TABLE program DROP CONSTRAINT FK_92ED778485B7874A');
    $this->addSql('DROP INDEX IDX_92ED7784CA76135A');
    $this->addSql('DROP INDEX IDX_92ED778485B7874A');
    $this->addSql('ALTER TABLE sampling DROP CONSTRAINT FK_39DAF8C6CA76135A');
    $this->addSql('ALTER TABLE sampling DROP CONSTRAINT FK_39DAF8C685B7874A');
    $this->addSql('DROP INDEX IDX_39DAF8C6CA76135A');
    $this->addSql('DROP INDEX IDX_39DAF8C685B7874A');
    $this->addSql('ALTER TABLE pcr DROP CONSTRAINT FK_5B6B9936CA76135A');
    $this->addSql('ALTER TABLE pcr DROP CONSTRAINT FK_5B6B993685B7874A');
    $this->addSql('DROP INDEX IDX_5B6B9936CA76135A');
    $this->addSql('DROP INDEX IDX_5B6B993685B7874A');
    $this->addSql('ALTER TABLE sampling_is_performed_by DROP CONSTRAINT FK_946D07C95E277EDA');
    $this->addSql('DROP INDEX pk_sampling_is_performed_by');
    $this->addSql('ALTER TABLE sampling_is_performed_by ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE sampling_is_performed_by ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_performed_by ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_performed_by ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_performed_by ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_performed_by ADD CONSTRAINT fk_65 FOREIGN KEY (sampling_fk) REFERENCES sampling (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE sampling_is_performed_by ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_946d07c9365cba19 RENAME TO idx_ee2a88c9b53cd04c');
    $this->addSql('ALTER INDEX idx_946d07c95e277eda RENAME TO idx_ee2a88c9662d9b98');
    $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD176CA76135A');
    $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD17685B7874A');
    $this->addSql('DROP INDEX IDX_34DCD176CA76135A');
    $this->addSql('DROP INDEX IDX_34DCD17685B7874A');
    $this->addSql('ALTER TABLE pcr_is_done_by DROP CONSTRAINT FK_7653C90F2B63D494');
    $this->addSql('DROP INDEX pk_pcr_is_done_by');
    $this->addSql('ALTER TABLE pcr_is_done_by ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE pcr_is_done_by ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE pcr_is_done_by ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE pcr_is_done_by ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE pcr_is_done_by ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE pcr_is_done_by ADD CONSTRAINT fk_21 FOREIGN KEY (pcr_fk) REFERENCES pcr (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE pcr_is_done_by ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_7653c90f2b63d494 RENAME TO idx_1041853b2b63d494');
    $this->addSql('ALTER INDEX idx_7653c90f365cba19 RENAME TO idx_1041853bb53cd04c');
    $this->addSql('ALTER TABLE municipality DROP CONSTRAINT FK_C6F56628CA76135A');
    $this->addSql('ALTER TABLE municipality DROP CONSTRAINT FK_C6F5662885B7874A');
    $this->addSql('DROP INDEX IDX_C6F56628CA76135A');
    $this->addSql('DROP INDEX IDX_C6F5662885B7874A');
    $this->addSql('ALTER TABLE sampling_is_done_with_method DROP CONSTRAINT FK_720F2A4F5E277EDA');
    $this->addSql('DROP INDEX pk_sampling_is_done_with_method');
    $this->addSql('ALTER TABLE sampling_is_done_with_method ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE sampling_is_done_with_method ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_done_with_method ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_done_with_method ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_done_with_method ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_done_with_method ADD CONSTRAINT fk_41 FOREIGN KEY (sampling_fk) REFERENCES sampling (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE sampling_is_done_with_method ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_720f2a4f29b38195 RENAME TO idx_5a6bd88a29b38195');
    $this->addSql('ALTER INDEX idx_720f2a4f5e277eda RENAME TO idx_5a6bd88a662d9b98');
    $this->addSql('ALTER TABLE sample_is_fixed_with DROP CONSTRAINT FK_1645AC245E277EDA');
    $this->addSql('DROP INDEX pk_sample_is_fixed_with');
    $this->addSql('ALTER TABLE sample_is_fixed_with ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE sample_is_fixed_with ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE sample_is_fixed_with ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE sample_is_fixed_with ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE sample_is_fixed_with ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE sample_is_fixed_with ADD CONSTRAINT fk_43 FOREIGN KEY (sampling_fk) REFERENCES sampling (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE sample_is_fixed_with ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_1645ac245e277eda RENAME TO idx_60129a31662d9b98');
    $this->addSql('ALTER INDEX idx_1645ac24a17a5d5 RENAME TO idx_60129a315fd841ac');
    $this->addSql('ALTER TABLE site DROP CONSTRAINT FK_694309E4CA76135A');
    $this->addSql('ALTER TABLE site DROP CONSTRAINT FK_694309E485B7874A');
    $this->addSql('DROP INDEX IDX_694309E4CA76135A');
    $this->addSql('DROP INDEX IDX_694309E485B7874A');
    $this->addSql('ALTER TABLE source_is_entered_by DROP CONSTRAINT FK_1399C909821B1D3F');
    $this->addSql('DROP INDEX pk_source_is_entered_by');
    $this->addSql('ALTER TABLE source_is_entered_by ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE source_is_entered_by ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE source_is_entered_by ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE source_is_entered_by ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE source_is_entered_by ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE source_is_entered_by ADD CONSTRAINT fk_29 FOREIGN KEY (source_fk) REFERENCES source (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE source_is_entered_by ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_1399c909365cba19 RENAME TO idx_16dc6005b53cd04c');
    $this->addSql('ALTER INDEX idx_1399c909821b1d3f RENAME TO idx_16dc6005821b1d3f');
    $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F73CA76135A');
    $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F7385B7874A');
    $this->addSql('DROP INDEX IDX_5F8A7F73CA76135A');
    $this->addSql('DROP INDEX IDX_5F8A7F7385B7874A');
    $this->addSql('ALTER TABLE species_is_identified_by DROP CONSTRAINT FK_F14051CB7607DC5C');
    $this->addSql('DROP INDEX pk_species_is_identified_by');
    $this->addSql('ALTER TABLE species_is_identified_by ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE species_is_identified_by ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE species_is_identified_by ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE species_is_identified_by ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE species_is_identified_by ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE species_is_identified_by ADD CONSTRAINT fk_9 FOREIGN KEY (identified_species_fk) REFERENCES identified_species (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE species_is_identified_by ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_f14051cb365cba19 RENAME TO idx_f8fccf63b53cd04c');
    $this->addSql('ALTER INDEX idx_f14051cb7607dc5c RENAME TO idx_f8fccf63b4ab6ba0');
    $this->addSql('ALTER TABLE specimen DROP CONSTRAINT FK_999F3902CA76135A');
    $this->addSql('ALTER TABLE specimen DROP CONSTRAINT FK_999F390285B7874A');
    $this->addSql('DROP INDEX IDX_999F3902CA76135A');
    $this->addSql('DROP INDEX IDX_999F390285B7874A');
    $this->addSql('ALTER TABLE taxon DROP CONSTRAINT FK_5B6723ABCA76135A');
    $this->addSql('ALTER TABLE taxon DROP CONSTRAINT FK_5B6723AB85B7874A');
    $this->addSql('DROP INDEX IDX_5B6723ABCA76135A');
    $this->addSql('DROP INDEX IDX_5B6723AB85B7874A');
    $this->addSql('ALTER TABLE storage_box DROP CONSTRAINT FK_932E7636CA76135A');
    $this->addSql('ALTER TABLE storage_box DROP CONSTRAINT FK_932E763685B7874A');
    $this->addSql('DROP INDEX IDX_932E7636CA76135A');
    $this->addSql('DROP INDEX IDX_932E763685B7874A');
    $this->addSql('ALTER TABLE user_db DROP CONSTRAINT FK_FBA308EDCA76135A');
    $this->addSql('ALTER TABLE user_db DROP CONSTRAINT FK_FBA308ED85B7874A');
    $this->addSql('DROP INDEX IDX_FBA308EDCA76135A');
    $this->addSql('DROP INDEX IDX_FBA308ED85B7874A');
    $this->addSql('ALTER TABLE sampling_is_funded_by DROP CONSTRAINT FK_427EDD595E277EDA');
    $this->addSql('DROP INDEX pk_sampling_is_funded_by');
    $this->addSql('ALTER TABLE sampling_is_funded_by ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE sampling_is_funded_by ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_funded_by ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_funded_by ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_funded_by ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE sampling_is_funded_by ADD CONSTRAINT fk_101 FOREIGN KEY (sampling_fk) REFERENCES sampling (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE sampling_is_funded_by ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_427edd59299f0654 RENAME TO idx_18fcbb8f759c7bb0');
    $this->addSql('ALTER INDEX idx_427edd595e277eda RENAME TO idx_18fcbb8f662d9b98');
    $this->addSql('ALTER TABLE vocabulary DROP CONSTRAINT FK_9099C97BCA76135A');
    $this->addSql('ALTER TABLE vocabulary DROP CONSTRAINT FK_9099C97B85B7874A');
    $this->addSql('DROP INDEX IDX_9099C97BCA76135A');
    $this->addSql('DROP INDEX IDX_9099C97B85B7874A');
    $this->addSql('ALTER TABLE specimen_slide DROP CONSTRAINT FK_ECF0B8FCA76135A');
    $this->addSql('ALTER TABLE specimen_slide DROP CONSTRAINT FK_ECF0B8F85B7874A');
    $this->addSql('DROP INDEX IDX_ECF0B8FCA76135A');
    $this->addSql('DROP INDEX IDX_ECF0B8F85B7874A');
    $this->addSql('ALTER TABLE dna_is_extracted_by DROP CONSTRAINT FK_876D7FE1918A8D9');
    $this->addSql('DROP INDEX pk_dna_is_extracted_by');
    $this->addSql('ALTER TABLE dna_is_extracted_by ADD id BIGSERIAL NOT NULL');
    $this->addSql('ALTER TABLE dna_is_extracted_by ADD date_of_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE dna_is_extracted_by ADD date_of_update TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    $this->addSql('ALTER TABLE dna_is_extracted_by ADD creation_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE dna_is_extracted_by ADD update_user_name BIGINT DEFAULT NULL');
    $this->addSql('ALTER TABLE dna_is_extracted_by ADD CONSTRAINT fk_23 FOREIGN KEY (dna_fk) REFERENCES dna (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE dna_is_extracted_by ADD PRIMARY KEY (id)');
    $this->addSql('ALTER INDEX idx_876d7fe1365cba19 RENAME TO idx_b786c521b53cd04c');
    $this->addSql('ALTER INDEX idx_876d7fe1918a8d9 RENAME TO idx_b786c5214b06319d');
    $this->addSql('ALTER TABLE institution DROP CONSTRAINT FK_3A9F98E5CA76135A');
    $this->addSql('ALTER TABLE institution DROP CONSTRAINT FK_3A9F98E585B7874A');
    $this->addSql('DROP INDEX IDX_3A9F98E5CA76135A');
    $this->addSql('DROP INDEX IDX_3A9F98E585B7874A');
  }
}
